package com.hib;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.cfg.Configuration;

import com.hib.to.Player;
import com.hib.to.Team;

/**
 * Hello world!
 *
 */
public class App {
	public static void main(String[] args) {
		
		try {
			Configuration configuration = new Configuration().configure();
			configuration.addAnnotatedClass(com.hib.to.Player.class);
			configuration.addAnnotatedClass(com.hib.to.Team.class);
			StandardServiceRegistryBuilder builder = new StandardServiceRegistryBuilder()
					.applySettings(configuration.getProperties());

			SessionFactory factory = configuration.buildSessionFactory(builder.build());

			Session session = factory.openSession();
			Transaction transaction = session.beginTransaction();
			
			//Create data in database
//			Player p1 = new Player(26, "Neeraj", "India", 24);
//			Player p2 = new Player(27, "Neeraj1", "India", 24);			
//			session.save(p1);
//			session.save(p2);
			
			//Read data from database
//			Player player = session.get(Player.class, 24);
//			System.out.println(player);
			
			//Update data of Database
//			Player player = session.get(Player.class, 24);
//			player.setPlayerName("Bhanu");
//			player.setTeamName("Kerla");
//			player.setAge(29);
			
			//Delete data from databases
//			Player player = session.get(Player.class, 25);
//			session.delete(player);
			
			
			//AutoGenerated Id
//			Player p1 = new Player("Durgesh", "India", 24);
//			Player p2 = new Player("Neeraj", "India", 24);
//			Player p3 = new Player("Prince", "India", 24);
//			Player p4 = new Player("Manish", "India", 24);
//			
//			session.save(p1);
//			session.save(p2);
//			session.save(p3);
//			session.save(p4);
			
			Team t1 = new Team("India");
			Team t2 = new Team("Australia");
			Player p1 = new Player("Virat",t1,29);
			Player p2 = new Player("Dhoni",t1,31);
			Player p3 = new Player("Ashwin",t1,30);
			Player p4 = new Player("Shane Watson",t2,42);
			session.save(t1);
			session.save(t2);
			session.save(p1);
			session.save(p2);
			session.save(p3);
			session.save(p4);
			
			transaction.commit();
			session.close();
		}
		catch (Exception e) {
			System.out.println(e.getMessage());
		}


	}
}
